#MATERIAS DE LA MALLA CURRICULAR

MATEMATICAS_I = "Matemáticas I"
MATEMATICAS_II = "Matemáticas II"
MATEMATICAS_III = "Matemáticas III"
FISICA_I = "Física I"
FISICA_II = "Física II"
ALGEBRA_LINEAL = "Algebra Lineal"
COMPUTACION_SOCIEDAD = "Computación y Sociedad"
ETICA = "Ética"
PROBABILIDAD_ESTADISTICA = "Probabilidad y Estadísticas"
MATEMATICAS_DISCRETAS = "Matemáticas Discretas"
TECNOLOGIAS_DISRUPTIVAS = "Tecnologías Disruptivas"
LOGICA_DIGITAL = "Lógica Digital"
BASE_DATOS_I = "Base de Datos I"
BASE_DATOS_II = "Base de Datos II"
FUNDAMENTOS_PROGRAMACION = "Fundamentos de Programación"
DESARROLLO_HUMANO = "Desarrollo Humano"
OAC = "Organización y Arquitectura de Computadores"
REDES_COMUNICACIONES = "Redes y Comunicaciones"
POO = "Programación Orientada a Objetos"
COMUNICACION_PROFESIONAL = "Comunicación e Imagen Profesional"
SISTEMAS_OPERATIVOS = "Sistemas Operativos"
DDS = "Diseño de Software"
LENGUAJES_PROGRAMACION = "Lenguajes de Programación"
ESTRUCTURA_DATOS = "Estructura de Datos"
DESARROLLO_SOSTENIBLE = "Desarrollo Sostenible"
SISTEMAS_DISTRIBUIDAS = "Sistemas Distribuidos"
INTERACCION_HM = "Interacción Hombre Máquina"
DESARROLLO_WEB = "Desarrollo de Aplicaciones Web"
ANALISIS_ALGORITMOS = "Análisis de Algoritmos"
LIDERAZGO_EMPRENDIMIENTO = "Liderazgo, Emprendimiento e Innovación"
PROCESAMIENTO_DATOS = "Procesamiento Masivo de Datos"
INGENIERIA_SOFTWARE_I = "Ingeniería de Software I"
INGENIERIA_SOFTWARE_II = "Ingeniería de Software II"
SISTEMAS_INTELIGENTES = "Sistemas Inteligentes"
PRACTICAS_COMUNITARIAS = "Practicas Comunitarias"
TITULACION_I = "Proyecto de Titulación I"
TITULACION_II = "Proyecto de Titulación II"
PRACTICAS_LABORALES = "Prácticas Laborales"
FUNDAMENTOS_FORENSES = "Fundamentos de Computación Forense"
ETHICAL_HACKING = "Ethical Hacking"

# SEMESTRES Y SUS MATERIAS

SEMESTRES = {
    1: [MATEMATICAS_I, FISICA_I, ALGEBRA_LINEAL, COMPUTACION_SOCIEDAD, ETICA],
    2: [MATEMATICAS_II, FISICA_II, PROBABILIDAD_ESTADISTICA, MATEMATICAS_DISCRETAS, TECNOLOGIAS_DISRUPTIVAS],
    3: [MATEMATICAS_III, LOGICA_DIGITAL, BASE_DATOS_I, FUNDAMENTOS_PROGRAMACION, DESARROLLO_HUMANO],
    4: [OAC, REDES_COMUNICACIONES, BASE_DATOS_II, POO, COMUNICACION_PROFESIONAL],
    5: [SISTEMAS_OPERATIVOS, DDS, LENGUAJES_PROGRAMACION, ESTRUCTURA_DATOS, DESARROLLO_SOSTENIBLE],
    6: [SISTEMAS_DISTRIBUIDAS, INTERACCION_HM, DESARROLLO_WEB, ANALISIS_ALGORITMOS, LIDERAZGO_EMPRENDIMIENTO],
    7: [PROCESAMIENTO_DATOS, INGENIERIA_SOFTWARE_I, SISTEMAS_INTELIGENTES, PRACTICAS_COMUNITARIAS, TITULACION_I],
    8: [ETHICAL_HACKING, INGENIERIA_SOFTWARE_II, FUNDAMENTOS_FORENSES, PRACTICAS_LABORALES, TITULACION_II]
}

# RELACIONES PARA LAS MATERIAS (PRE-REQUISITOS)

RELACIONES = [
    # Primer Semestre
    (MATEMATICAS_I, MATEMATICAS_II), (FISICA_I, FISICA_II), (ALGEBRA_LINEAL, PROBABILIDAD_ESTADISTICA), (COMPUTACION_SOCIEDAD, MATEMATICAS_DISCRETAS),
    # Segundo Semestre
    (MATEMATICAS_II, MATEMATICAS_III), (FISICA_II, LOGICA_DIGITAL), (PROBABILIDAD_ESTADISTICA, LOGICA_DIGITAL), (MATEMATICAS_DISCRETAS, FUNDAMENTOS_PROGRAMACION), (TECNOLOGIAS_DISRUPTIVAS, BASE_DATOS_I), (TECNOLOGIAS_DISRUPTIVAS, FUNDAMENTOS_PROGRAMACION),
    # Tercer Semestre
    (MATEMATICAS_III, REDES_COMUNICACIONES), (LOGICA_DIGITAL, OAC), (LOGICA_DIGITAL, REDES_COMUNICACIONES), (BASE_DATOS_I, BASE_DATOS_II), (FUNDAMENTOS_PROGRAMACION, BASE_DATOS_I), (FUNDAMENTOS_PROGRAMACION, POO),
    # Cuarto Semestre
    (OAC, SISTEMAS_OPERATIVOS), (REDES_COMUNICACIONES, SISTEMAS_OPERATIVOS), (BASE_DATOS_II, DESARROLLO_WEB), (POO, SISTEMAS_OPERATIVOS), (POO, DDS), (POO, LENGUAJES_PROGRAMACION), (POO, ESTRUCTURA_DATOS), 
    # Quinto Semestre
    (SISTEMAS_OPERATIVOS, SISTEMAS_DISTRIBUIDAS), (DDS, DESARROLLO_WEB), (LENGUAJES_PROGRAMACION, DDS), (LENGUAJES_PROGRAMACION, DESARROLLO_WEB), (ESTRUCTURA_DATOS, LENGUAJES_PROGRAMACION), (ESTRUCTURA_DATOS, ANALISIS_ALGORITMOS),
    # Sexto Semestre
    (SISTEMAS_DISTRIBUIDAS, PROCESAMIENTO_DATOS), (SISTEMAS_DISTRIBUIDAS, SISTEMAS_INTELIGENTES), (INTERACCION_HM, INGENIERIA_SOFTWARE_I), (DESARROLLO_WEB, INTERACCION_HM), (DESARROLLO_WEB, SISTEMAS_INTELIGENTES), (ANALISIS_ALGORITMOS, SISTEMAS_INTELIGENTES),
    # Séptimo Semestre
    (PROCESAMIENTO_DATOS, ETHICAL_HACKING), (PROCESAMIENTO_DATOS, TITULACION_I), (PROCESAMIENTO_DATOS, TITULACION_II), (INGENIERIA_SOFTWARE_I, INGENIERIA_SOFTWARE_II), (SISTEMAS_INTELIGENTES, FUNDAMENTOS_FORENSES), (SISTEMAS_INTELIGENTES, TITULACION_I), (SISTEMAS_INTELIGENTES, TITULACION_II), (TITULACION_I, TITULACION_II),
    # Octavo Semestre
    (ETHICAL_HACKING, TITULACION_I), (ETHICAL_HACKING, TITULACION_II), (INGENIERIA_SOFTWARE_II, TITULACION_I), (INGENIERIA_SOFTWARE_II, TITULACION_II), (FUNDAMENTOS_FORENSES, TITULACION_I), (FUNDAMENTOS_FORENSES, TITULACION_II)
]

# COLORES PARA LOS NODOS DE LA MALLA CURRICULAR (AZUL-UNIDAD BASICA, MORADO-UNIDAD PROFESIONAL, VERDE-INTEGRACION CURRICULAR)

COLOR_NODOS = {}
for semestre in [1, 2, 3]:
    for materia in SEMESTRES[semestre]:
        COLOR_NODOS[materia] = "#a7d8f0"
        if materia == BASE_DATOS_I:
            COLOR_NODOS[materia] = "#c8b3e6"
for semestre in [4, 5, 6, 7, 8]:
    for materia in SEMESTRES[semestre]:
        COLOR_NODOS[materia] = "#c8b3e6"
        if materia in [COMUNICACION_PROFESIONAL, DESARROLLO_SOSTENIBLE, LIDERAZGO_EMPRENDIMIENTO]:
            COLOR_NODOS[materia] = "#a7d8f0"
for materia in [TITULACION_I, TITULACION_II]:
    COLOR_NODOS[materia] = "#b6e7b0"

# HORAS DEDICADAS A CADA MATERIA

HORAS = {
    TITULACION_I: "192 Horas",
    TITULACION_II: "96 Horas",
    PRACTICAS_COMUNITARIAS: "96 Horas",
    PRACTICAS_LABORALES: "240 Horas",
    INGENIERIA_SOFTWARE_II: "96 Horas"
}

for materias in SEMESTRES.values():
    for m in materias:
        if m not in HORAS:
            HORAS[m] = "144 Horas"