import networkx as nx
import matplotlib.pyplot as plt
import src.utils.consts

def getMalla():
    malla = nx.DiGraph()

    materias = [
        # Año 1
        # Primer Semestre
        MATEMATICAS_I, FISICA_I, ALGEBRA_LINEAL, COMPUTACION_SOCIEDAD, ETICA,
        # Segundo Semestre
        MATEMATICAS_II, FISICA_II, PROBABILIDAD_ESTADISTICA, MATEMATICAS_DISCRETAS, TECNOLOGIAS_DISRUPTIVAS,
        # Año 2
        # Tercer Semestre
        MATEMATICAS_III, LOGICA_DIGITAL, BASE_DATOS_I, FUNDAMENTOS_PROGRAMACION, DESARROLLO_HUMANO,
        # Cuarto Semestre
        OAC, REDES_COMUNICACIONES, BASE_DATOS_II, POO, COMUNICACION_PROFESIONAL,
        # Año 3
        # Quinto Semestre
        SISTEMAS_OPERATIVOS, DDS, POO, ESTRUCTURA_DATOS, DESARROLLO_HUMANO,
        # Sexto Semestre
        SISTEMAS_DISTRIBUIDAS, INTERACCION_HM, DESARROLLO_WEB, ANALISIS_ALGORITMOS, LIDERAZGO_EMPRENDIMIENTO,
        # Año 4
        # Septimo Semestre
        PROCESAMIENTO_DATOS, INGENIERIA_SOFTWARE_I, SISTEMAS_INTELIGENTES, PRACTICAS_COMUNITARIAS, TITULACION_I
        # Octavo Semestre
        ETHICAL_HACKING, INGENIERIA_SOFTWARE_II, FUNDAMENTOS_FORENSES, PRACTICAS_LABORALES, TITULACION_II
    ]

    malla.add_nodes_from(materias)
    
    relaciones = [
        # Primer Semestre
        (MATEMATICAS_I, MATEMATICAS_II), (FISICA_I, FISICA_II), (ALGEBRA_LINEAL, PROBABILIDAD_ESTADISTICA), (COMPUTACION_SOCIEDAD, MATEMATICAS_DISCRETAS),
        # Segundo Semestre
        (MATEMATICAS_II, MATEMATICAS_III), (FISICA_II, LOGICA_DIGITAL), (PROBABILIDAD_ESTADISTICA, LOGICA_DIGITAL), (MATEMATICAS_DISCRETAS, FUNDAMENTOS_PROGRAMACION), (TECNOLOGIAS_DISRUPTIVAS, BASE_DATOS_I), (TECNOLOGIAS_DISRUPTIVAS, FUNDAMENTOS_PROGRAMACION),
        # Tercer Semestre
        (MATEMATICAS_III, REDES_COMUNICACIONES), (LOGICA_DIGITAL, OAC), (LOGICA_DIGITAL, REDES_COMUNICACIONES), (BASE_DATOS_I, BASE_DATOS_II), (FUNDAMENTOS_PROGRAMACION, BASE_DATOS_I), (FUNDAMENTOS_PROGRAMACION, POO),
        # Cuarto Semestre
        (OAC, SISTEMAS_OPERATIVOS), (REDES_COMUNICACIONES, SISTEMAS_OPERATIVOS), (BASE_DATOS_II, DESARROLLO_WEB), (POO, SISTEMAS_OPERATIVOS), (POO, DDS), (POO, LENGUAJES_PROGRAMACION), (POO, ESTRUCTURA_DATOS), 
        # Quinto Semestre
        (SISTEMAS_OPERATIVOS, SISTEMAS_DISTRIBUIDAS), (DDS, DESARROLLO_WEB), (LENGUAJES_PROGRAMACION, DDS), (LENGUAJES_PROGRAMACION, DESARROLLO_WEB), (ESTRUCTURA_DATOS, LENGUAJES_PROGRAMACION), (ESTRUCTURA_DATOS, ANALISIS_ALGORITMOS),
        # Sexto Semestre
        (SISTEMAS_DISTRIBUIDAS, PROCESAMIENTO_DATOS), (SISTEMAS_DISTRIBUIDAS, SISTEMAS_INTELIGENTES), (INTERACCION_HM, INGENIERIA_SOFTWARE_I), (DESARROLLO_WEB, INTERACCION_HM), (DESARROLLO_WEB, SISTEMAS_INTELIGENTES), (ANALISIS_ALGORITMOS, SISTEMAS_INTELIGENTES),
        # Séptimo Semestre
        (PROCESAMIENTO_DATOS, ETHICAL_HACKING), (PROCESAMIENTO_DATOS, TITULACION_I), (PROCESAMIENTO_DATOS, TITULACION_II), (INGENIERIA_SOFTWARE_I, INGENIERIA_SOFTWARE_II), (SISTEMAS_INTELIGENTES, FUNDAMENTOS_FORENSES), (SISTEMAS_INTELIGENTES, TITULACION_I), (SISTEMAS_INTELIGENTES, TITULACION_II), (TITULACION_I, TITULACION_II),
        # Octavo Semestre
        (ETHICAL_HACKING, TITULACION_I), (ETHICAL_HACKING, TITULACION_II), (INGENIERIA_SOFTWARE_II, TITULACION_I), (INGENIERIA_SOFTWARE_II, TITULACION_II), (FUNDAMENTOS_FORENSES, TITULACION_I), (FUNDAMENTOS_FORENSES, TITULACION_II)
    ]

    malla.add_edges_from(relaciones)
    
    return malla
